name: Write to Excel with Node.js

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  write-excel:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Node.js をセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 必要パッケージをインストール
        run: npm install xlsx

      - name: Node.js スクリプトで Excel を書き込み
        run: node -e '
          const XLSX = require("xlsx");
          const fs = require("fs");

          const filePath = "data.xlsx";
          let workbook;
          try {
            workbook = XLSX.readFile(filePath);
          } catch (e) {
            workbook = XLSX.utils.book_new();
          }
          const sheetName = "Sheet1";
          let sheet = workbook.Sheets[sheetName] || XLSX.utils.aoa_to_sheet([["A1"]]);

          sheet["A1"] = { t: "s", v: "Hello from GitHub Actions!" };

          workbook.Sheets[sheetName] = sheet;
          XLSX.writeFile(workbook, filePath);
        '

      - name: Excel ファイルをアーティファクトとしてアップロード
        uses: actions/upload-artifact@v4
        with:
          name: excel-file
          path: data.xlsx
