name: Write to Excel with Node.js

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  write-excel:
    runs-on: ubuntu-latest #ubuntuを立ち上げ。Github Actionsは毎回まっさらな仮想マシンを立ち上げる

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4 #git cloneした状態

      - name: Node.js をセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # 必要なNode.jsバージョンを指定

      - name: 依存パッケージをインストール
        run: npm install xlsx

      - name: Node.js スクリプトを実行（Excel 書き込み）
        run: node -e '
          const XLSX = require("xlsx");
          const fs = require("fs");

          const filePath = "data.xlsx";
          let workbook;
          try {
            workbook = XLSX.readFile(filePath);
          } catch (e) {
            workbook = XLSX.utils.book_new();
          }
          const sheetName = "Sheet1";
          let sheet = workbook.Sheets[sheetName] || XLSX.utils.aoa_to_sheet([["A1"]]);

          sheet["A1"] = { t: "s", v: "Hello from GitHub Actions!" };

          workbook.Sheets[sheetName] = sheet;
          XLSX.writeFile(workbook, filePath);

          console.log("Excel にデータを書き込みました:", filePath);
        '

      - name: Excel ファイルを GitHub にコミット
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.xlsx
          git commit -m "Update Excel file"
          git push origin main
        continue-on-error: true  # 変更がない場合はスキップ
