name: Write to Excel with Node.js

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  write-excel:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Node.js をセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 依存パッケージをインストール
        run: npm install xlsx

      - name: Node.js スクリプトを実行（Excel 書き込み）
        run: node .github/scripts/writeExcel.js

      - name: Excel ファイルをアーティファクトとして保存
        uses: actions/upload-artifact@v4  # ✅ v4 に更新
        with:
          name: excel-output
          path: data.xlsx
